version: '3'

services:
  database:
    container_name: ecology-database
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecology
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  server:
    depends_on:
      - database
    build: .
    container_name: ecology-server
    ports:
      - '4200:4200'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ecology-database:5432/ecology?schema=public

volumes:
  database: