openapi: 3.0.0

info:
  title: Ecology App API
  version: 1.0.0

tags:
  - name: Authorization
    description: Authorization endpoints

paths:
  /api/auth/register:
    post:
      tags:
        - Authorization
      summary: Registers a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: JSON Web Token
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  data:
                    type: object
                    properties:
                      token:
                        type: string
              example:
                status: 201
                data:
                  token: token
  /api/auth/login:
    post:
      tags:
        - Authorization
      summary: Signs user in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: JSON Web Token
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  data:
                    type: object
                    properties:
                      token:
                        type: string
              example:
                status: 200
                data:
                  token: token
